### PR TITLE
History example

### PR DESCRIPTION
**Pull request by michielbdejong**

### CODE REVIEW

**Comment by michielbdejong** [comment]
@MattiSG @Ndpnt example of the versions history my script now creates. Anything you want changed?

**Comment by Ndpnt** [comment]
> @MattiSG @Ndpnt example of the versions history my script now creates. Anything you want changed?

[As for the snapshot repo](https://github.com/ambanum/CGUs-snapshots/pull/3#issuecomment-683784752), I suggest to modify the message.
Also can you add a link to the snapshot commit id like we currently do? For example:
```
Update AmazonFreeTimeUnlimited Terms of Service (Thu Apr 09 2020)

This version was recorded after filtering snapshot https://github.com/ambanum/CGUs-snapshots/commit/$commit-id
```

**Comment by MattiSG** [comment]
I'd be in favor of putting the original date in its own line in ISO format, to ease potential future parsing and limit the length of the subject line 🙂 

```
Update AmazonFreeTimeUnlimited Terms of Service

This version was recorded after filtering snapshot https://github.com/ambanum/CGUs-snapshots/commit/$commit-id
Snapshot originally obtained on 2020-04-09
```

**Comment by MattiSG** [comment]
I see that there is no distinction between “start tracking” and “update”, while there is in the current codebase.
It's not a blocking issue for me, but it would sure be welcome, as it can both help with potential future automated parsing and improves the current user experience (it shows that there is no past).

**Comment by michielbdejong** [comment]
We should also edit the "old first version" when we rebase, because it will become an update and not a start

**Comment by michielbdejong** [comment]
Changed adopted in https://github.com/ambanum/TOSBack-CGUs-bridge

**Pull request closed without merging**
